name: Build MiniPlasma

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore MiniPlasma/PoC_AbortHydration_ArbitraryRegKey_EoP.sln

      - name: Build solution
        run: msbuild MiniPlasma/PoC_AbortHydration_ArbitraryRegKey_EoP.sln /p:Configuration=Release /p:Platform="Any CPU" /p:SignManifests=false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiniPlasma-Release
          path: MiniPlasma/PoC_AbortHydration_ArbitraryRegKey_EoP/bin/Release/